#!/bin/sh
#SBATCH --job-name=matlab
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-user=fabien.pierre@math.u-bordeaux.fr
#SBATCH -o matlab%j.out
#SBATCH -e matlab%j.err
#SBATCH --time=3-00:00:00
#SBATCH --exclusive
#SBATCH -N 1
#SBATCH --tasks-per-node 1
#SBATCH -p longq


module add compiler/gcc/4.8.4
module add tools/matlab

cd /home/fpierre/flot_optique

time matlab -nodisplay < MS_flotoptique.m > ./print.res
